[versions]
agp = "8.2.0"
apksig = "8.2.0"
libsu = "5.2.2"
guava = "32.1.3-jre"
jsoup = "1.17.1"
kotlin = "1.9.21"
kotlinx-coroutines-android = "1.7.3"
compose-compiler = "1.5.6"

activity-ktx = "1.8.2"
androidx-documentfile = "1.1.0-alpha01"
coil-compose = "2.5.0"
navigation-compose = "2.7.6"
osmdroid-android = "6.1.17"
recyclerview = "1.3.2"

compose-bom = "2023.10.01"
bcprov-jdk18on = "1.77"
dexlib2 = "2.5.2"
ffmpeg-kit = "5.1.LTS" # DO NOT UPDATE FFMPEG-KIT TO "5.1" it breaks stuff :3
gson = "2.10.1"
junit = "4.13.2"
material3 = "1.1.2"
okhttp = "5.0.0-alpha.11"
rhino = "1.7.14"


[libraries]
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
androidx-activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "activity-ktx" }
androidx-documentfile = { group = "androidx.documentfile", name = "documentfile", version.ref = "androidx-documentfile" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
androidx-material-icons-core = { module = "androidx.compose.material:material-icons-core" }
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
androidx-material-ripple = { module = "androidx.compose.material:material-ripple" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation-compose" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
apksig = { module = "com.android.tools.build:apksig", version.ref = "apksig" }
bcprov-jdk18on = { module = "org.bouncycastle:bcprov-jdk18on", version.ref = "bcprov-jdk18on" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil-compose" }
coil-video = { module = "io.coil-kt:coil-video", version.ref = "coil-compose" }
libsu = { module = "com.github.topjohnwu.libsu:core", version.ref = "libsu" }
coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinx-coroutines-android" }
dexlib2 = { group = "org.smali", name = "dexlib2", version.ref = "dexlib2" }
ffmpeg-kit = { group = "com.arthenica", name = "ffmpeg-kit-full-gpl", version.ref = "ffmpeg-kit" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
junit = { module = "junit:junit", version.ref = "junit" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
osmdroid-android = { group = "org.osmdroid", name = "osmdroid-android", version.ref = "osmdroid-android" }
recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
rhino = { module = "org.mozilla:rhino", version.ref = "rhino" }


[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }


[bundles]
