name: Android CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Clean Gradle Cache
      run: ./gradlew clean
    - name: Get keystore from secrets and decode base64
      run: echo ${{ secrets.JAVA_KEYSTORE_DATA }} | base64 --decode > $GITHUB_WORKSPACE/signing.jks
    - name: Build with Gradle
      run: ./gradlew assembleRelease -PtargetApkUrl=${{ secrets.TARGET_APK_URL }} -Pandroid.injected.signing.store.file="$GITHUB_WORKSPACE/signing.jks" -Pandroid.injected.signing.store.password="${{ secrets.KEYSTORE_PASSWORD }}" -Pandroid.injected.signing.key.alias="${{ secrets.KEY_ALIAS }}" -Pandroid.injected.signing.key.password="${{ secrets.KEY_PASSWORD }}"
    - name: Upload armv8
      uses: actions/upload-artifact@v3.1.2
      with:
        name: app-armv8-release
        path: app/build/outputs/apk/armv8/release/*.apk
    - name: Upload armv7
      uses: actions/upload-artifact@v3.1.2
      with:
        name: app-armv7-release
        path: app/build/outputs/apk/armv7/release/*.apk
    - name: Upload prod
      uses: actions/upload-artifact@v3.1.2
      with:
        name: app-prod-release
        path: app/build/outputs/apk/prod/release/*.apk
    - name: Upload lspatch
      uses: actions/upload-artifact@v3.1.2
      with:
        name: app-lspatch-release
        path: app/build/outputs/apk/lspatch/release/*.apk
